# application: gpggeosci
# version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# cert
# - url: /.well-known/acme-challenge
#   static_dir: letsencrypt

# favicon
- url: /favicon\.ico
  static_files: gpg.ico
  upload: gpg\.ico
  secure: always

# all css
- url: /(.*\.css)
  mime_type: text/css
  static_files: _build/html/\1
  upload: _build/html/(.*\.css)
  secure: always

# webfonts
- url: /(.*\.(eot|svg|ttf|woff|woff2|otf))
  static_files: _build/html/\1
  upload: _build/html/(.*\.(eot|svg|ttf|woff|woff2|otf))
  secure: always

# javascript
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: _build/html/\1
  upload: _build/html/(.*\.js)
  secure: always

# plain text source
- url: /(.*\.txt)
  mime_type: text/plain
  static_files: _build/html/\1
  upload: _build/html/(.*\.txt)
  secure: always

  # python source files
- url: /(.*\.py)
  static_files: _build/html/\1
  upload: _build/html/(.*\.py)
  secure: always

# images
- url: /_images/(.*\.(gif|png|jpg|ico))
  static_files: _build/html/_images/\1
  upload: _build/html/_images/(.*\.(gif|png|jpg|ico))
  secure: always

# redirect en/latest traffic
- url: /en/latest/(.*\.html)
  script: gpggeosci.app
  secure: always

# raw html
- url: /(.*\.html)
  mime_type: text/html
  static_files: _build/html/\1
  upload: _build/html/(.*\.html)
  secure: always

# serve index files
- url: /(.+)/
  static_files: _build/html/\1/index.html
  upload: _build/html/(.+)/index.html
  secure: always

- url: /(.+)
  static_files: _build/html/\1/index.html
  upload: _build/html/(.+)/index.html
  secure: always

- url: /
  static_files: _build/html/index.html
  upload: _build/html/index.html
  secure: always

- url: /.*
  static_files: _templates/error.html
  upload: _templates/error.html
  secure: always

- url: .*
  script: gpggeosci.app
  secure: always

# Recommended file skipping declaration from the GAE tutorials
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^(.*/)?.*\.doctree$
  - ^(.*)\.docx

libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: "1.1.7"
- name: numpy
  version: "latest"
- name: jinja2
  version: "latest"
